# Generated by Django 6.0.6 on 2026-06-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='competetion',
            new_name='competition',
        ),
    ]
