# Generated by Django 6.0.6 on 2026-06-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0002_rename_competetion_match_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="fromation",
            field=models.CharField(default="4-3-3", max_length=10),
        ),
    ]
