# Generated by Django 6.0.6 on 2026-06-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0003_match_fromation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="fromation",
            new_name="formation",
        ),
    ]
