# Generated by Django 6.0.6 on 2026-06-11 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puzzles', '0002_rename_competetion_match_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('attempts_used', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('share_text', models.TextField(blank=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.anonymoususer')),
            ],
            options={
                'unique_together': {('user', 'puzzle')},
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('was_correct', models.BooleanField(default=False)),
                ('hint_revealed', models.JSONField(blank=True, null=True)),
                ('guessed_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='puzzles.player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='users.userresult')),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
    ]
